/* <p>Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with $1$ and $2$, the first $10$ terms will be:
$$1, 2, 3, 5, 8, 13, 21, 34, 55, 89, \dots$$</p>
<p>By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.</p> */

function sumEvenFibo(limit){
    let sum = 0;
    let prev = 1;
    let current = 2;

    while(current<=limit){
        if(current%2 === 0){
            sum += current;
        }
        const next = prev + current;
        prev = current;
        current = next;
    }
    return sum;
}
l = 4000000
console.log(sumEvenFibo(l));